
# Generated by xtables-save v1.8.2 on Thu Oct  3 01:18:13 2019
# Generated by xtables-save v1.8.2 on Thu Oct  3 01:18:13 2019
### *nat
### :PREROUTING ACCEPT [60753:13459711]
### :INPUT ACCEPT [17438:1130615]
### :POSTROUTING ACCEPT [9215:602254]
### :OUTPUT ACCEPT [14257:950975]
### :DOCKER - [0:0]
### [5:280] -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
### [0:0] -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
### [0:0] -A POSTROUTING -s 172.18.0.0/16 ! -o docker_gwbridge -j MASQUERADE
### [0:0] -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
### [0:0] -A DOCKER -i docker0 -j RETURN
### [0:0] -A DOCKER -i docker_gwbridge -j RETURN
### COMMIT
# Completed on Thu Oct  3 01:18:13 2019

class docker::firewall::docker_nat {

  # -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER 
  firewall { '00107 DOCKER table PREROUTING LOCAL traffic':
    dst_type => 'LOCAL',
    table    => 'nat',
    proto    => 'all',
    chain    => 'PREROUTING',
    jump     => 'DOCKER',
  }

  # -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER 
  firewall { '00108 DOCKER chain, route LOCAL non-loopback traffic to DOCKER':
    table       => 'nat',
    dst_type    => 'LOCAL',
    chain       => 'OUTPUT',
    proto       => 'all',
    destination => '! 127.0.0.1/8',
    jump        => 'DOCKER',
  }

  # -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
  firewall { '00109 DOCKER chain, MASQUERADE docker bridge traffic not bound to docker bridge':
    table    => 'nat',
    chain    => 'POSTROUTING',
    proto    => 'all',
    source   => "${::network_docker0}/16",
    outiface => '! docker0',
    jump     => 'MASQUERADE',
  }

  # -A POSTROUTING -s 172.18.0.0/16 ! -o docker_gwbridge -j MASQUERADE
  firewall { '00109 DOCKER chain, MASQUERADE docker_gwbridge traffic not bound to docker bridge':
    table    => 'nat',
    chain    => 'POSTROUTING',
    proto    => 'all',
    source   => "${::network_docker_gwbridge}/16",
    outiface => '! docker_gwbridge',
    jump     => 'MASQUERADE',
  }

  # -A DOCKER -i docker0 -j RETURN
  firewall { '00110 DOCKER chain, RETURN and remaining docker bridge packets':
    table   => 'nat',
    chain   => 'DOCKER',
    proto   => 'all',
    iniface => 'docker0',
    jump    => 'RETURN',
  }

  # -A DOCKER -i docker_gwbridge -j RETURN
  firewall { '00110 DOCKER chain, RETURN any remaining docker_gwbridge packets':
    table   => 'nat',
    chain   => 'DOCKER',
    proto   => 'all',
    iniface => 'docker_gwbridge',
    jump    => 'RETURN',
  }

}

