# Generated by xtables-save v1.8.2 on Thu Oct  3 01:18:13 2019
### *filter
### :INPUT ACCEPT [26123:8603155]
### :FORWARD ACCEPT [0:0]
### :OUTPUT ACCEPT [471819:146025618]
### :DOCKER - [0:0]
### :DOCKER-ISOLATION-STAGE-1 - [0:0]
### :DOCKER-ISOLATION-STAGE-2 - [0:0]
### :DOCKER-USER - [0:0]
### [0:0] -A FORWARD -j DOCKER-USER
### [0:0] -A FORWARD -j DOCKER-ISOLATION-STAGE-1
### [0:0] -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
### [0:0] -A FORWARD -o docker0 -j DOCKER
### [0:0] -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
### [0:0] -A FORWARD -i docker0 -o docker0 -j ACCEPT
### [0:0] -A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
### [0:0] -A FORWARD -o docker_gwbridge -j DOCKER
### [0:0] -A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
### [0:0] -A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
### [0:0] -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
### [0:0] -A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
### [0:0] -A DOCKER-ISOLATION-STAGE-1 -j RETURN
### [0:0] -A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
### [0:0] -A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
### [0:0] -A DOCKER-ISOLATION-STAGE-2 -j RETURN
### [0:0] -A DOCKER-USER -j RETURN
### COMMIT
# Completed on Thu Oct  3 01:18:13 2019

class docker::firewall::docker_filter {

    # The namevar here is in the format chain_name:table:protocol
    firewallchain { 'DOCKER:filter:IPv4':
      ensure  => present,
    }

    firewallchain { 'DOCKER-USER:filter:IPv4':
      ensure  => present,
    }

    firewallchain { 'DOCKER-ISOLATION-STAGE-1:filter:IPv4':
      ensure  => present,
    }

    firewallchain { 'DOCKER-ISOLATION-STAGE-2:filter:IPv4':
      ensure  => present,
    }

    # -A FORWARD -j DOCKER-USER
    firewall { '00101 forward to DOCKER-USER':
      chain => 'FORWARD',
      proto => 'all',
      jump  => 'DOCKER-USER',
    }

    # -A FORWARD -j DOCKER-ISOLATION-STAGE-1
    firewall { '00102 forward to DOCKER-ISOLATION-STAGE-1':
      chain => 'FORWARD',
      proto => 'all',
      jump  => 'DOCKER-ISOLATION-STAGE-1',
    }

    # -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    firewall { '00103 accept related, established traffic returning to docker0 bridge in FORWARD chain':
      action   => 'accept',
      proto    => 'all',
      chain    => 'FORWARD',
      outiface => 'docker0',
      ctstate  => ['RELATED','ESTABLISHED'],
    }

    # -A FORWARD -o docker0 -j DOCKER
    firewall { '00104 forward to DOCKER':
      chain    => 'FORWARD',
      proto    => 'all',
      outiface => 'docker0',
      jump     => 'DOCKER',
    }

    # -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
    firewall { '00105 accept docker0 traffic to other interfaces on FORWARD chain':
      action   => 'accept',
      proto    => 'all',
      chain    => 'FORWARD',
      iniface  => 'docker0',
      outiface => '! docker0',
    }

    # -A FORWARD -i docker0 -o docker0 -j ACCEPT
    firewall { '00106 accept docker0 to docker0 FORWARD traffic':
      action   => 'accept',
      proto    => 'all',
      chain    => 'FORWARD',
      iniface  => 'docker0',
      outiface => 'docker0',
    }

    # -A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
    firewall { '00111 DOCKER-ISOLATION-STAGE-1 docker0 traffic bound elsewhere, forward to DOCKER-ISOLATION-STAGE-2':
      chain    => 'DOCKER-ISOLATION-STAGE-1',
      iniface  => 'docker0',
      outiface => '! docker0',
      proto    => 'all',
      jump     => 'DOCKER-ISOLATION-STAGE-2',
    }

    # -A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    firewall { '00106 accept docker_gwbridge traffic related to established connections':
      action   => 'accept',
      proto    => 'all',
      chain    => 'FORWARD',
      outiface => 'docker_gwbridge',
      ctstate  => ['RELATED','ESTABLISHED'],
    }

    # -A FORWARD -o docker_gwbridge -j DOCKER
    firewall { '00106 forward docker_gwbridge traffic to DOCKER chain':
      jump     => 'DOCKER',
      proto    => 'all',
      chain    => 'FORWARD',
      outiface => 'docker_gwbridge',
    }

    # -A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
    firewall { '00106 accept ingress docker_gwbridge traffic not destined for another docker_gwbridge route':
      action   => 'accept',
      proto    => 'all',
      chain    => 'FORWARD',
      iniface  => 'docker_gwbridge',
      outiface => '! docker_gwbridge',
    }

    # -A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
    firewall { '00106 drop traffic from and to the docker_gwbridge network':
      action   => 'drop',
      proto    => 'all',
      chain    => 'FORWARD',
      outiface => 'docker_gwbridge',
      iniface  => 'docker_gwbridge',
    }

    # -A DOCKER-ISOLATION-STAGE-1 -i docker_gwbridge ! -o docker_gwbridge -j DOCKER-ISOLATION-STAGE-2
    firewall { '00106 route DOCKER-ISOLATION-STAGE-1 traffic to DOCKER-ISOLATION-STAGE-2':
      jump     => 'DOCKER-ISOLATION-STAGE-2',
      proto    => 'all',
      chain    => 'DOCKER-ISOLATION-STAGE-1',
      outiface => '! docker_gwbridge',
      iniface  => 'docker_gwbridge',
    }

    # -A DOCKER-ISOLATION-STAGE-2 -o docker_gwbridge -j DROP
    firewall { '60111 drop docker_gwbridge egress traffic left in the DOCKER-ISOLATION-STAGE-2 chain':
      action   => 'drop',
      proto    => 'all',
      chain    => 'DOCKER-ISOLATION-STAGE-2',
      outiface => 'docker_gwbridge',
    }

    # -A DOCKER-ISOLATION-STAGE-1 -j RETURN
    firewall { '60112 DOCKER-ISOLATION-STAGE-1 traffic RETURNs':
      chain => 'DOCKER-ISOLATION-STAGE-1',
      proto => 'all',
      jump  => 'RETURN',
    }

    # -A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
    firewall { '60113 DOCKER-ISOLATION-STAGE-2 traffic heading back to docker0 bridge is DROPed':
      chain    => 'DOCKER-ISOLATION-STAGE-2',
      outiface => 'docker0',
      proto    => 'all',
      action   => 'drop',
    }

    # -A DOCKER-ISOLATION-STAGE-2 -j RETURN
    firewall { '60114 DOCKER-ISOLATION-STAGE-2 traffic now RETURNed':
      chain => 'DOCKER-ISOLATION-STAGE-2',
      jump  => 'RETURN',
    }

    # -A DOCKER-USER -j RETURN
    firewall { '60115 DOCKER-USER traffic now RETURNed':
      chain => 'DOCKER-USER',
      jump  => 'RETURN',
    }

}

